# Generated by Django 4.2.7 on 2023-11-03 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_appuser_is_active_appuser_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='user_id',
            new_name='id',
        ),
    ]
